version: "3.7"

services:
  traefik:
    image: traefik:latest
    command:
      - --api.dashboard=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencryptresolver.acme.httpchallenge=true
      - --certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencryptresolver.acme.email=webmaster@companhiaweb.com.br
      - --certificatesresolvers.letsencryptresolver.acme.storage=/etc/traefik/letsencrypt/acme.json
      - --log.level=DEBUG
      - --log.format=common
      - --log.filePath=/var/log/traefik/traefik.log
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access-log
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.redirect-https.redirectscheme.scheme=https
        - traefik.http.middlewares.redirect-https.redirectscheme.permanent=true
        - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
        - traefik.http.routers.http-catchall.entrypoints=web
        - traefik.http.routers.http-catchall.middlewares=redirect-https@docker
        - traefik.http.routers.http-catchall.priority=1
        # Traefik dashboard
        - traefik.http.routers.traefik-api.rule=Host(`traefik.cw.srv.br`)
        - traefik.http.routers.traefik-api.service=api@internal
        - traefik.http.routers.traefik-api.entrypoints=websecure
        - traefik.http.routers.traefik-api.priority=1
        - traefik.http.routers.traefik-api.tls=true
        - traefik.http.routers.traefik-api.tls.certresolver=letsencryptresolver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - le_certificates:/etc/traefik/letsencrypt
      - /var/log/traefik/traefik.log:/var/log/traefik/traefik.log
      - /var/log/traefik/access-log:/var/log/traefik/access-log
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - proxy

volumes:
  le_certificates:
    external: true
    name: le_certificates

networks:
  proxy:
    external: true
    name: proxy

